# K-Means

```{note}
K-Means iterative update cluster centroids and instances label.<br/>
K-Means is convergent.<br/>
We can use inertia to select the number of clusters.<br/>
We can use mini-batch K-means to enable clustering huge datasets.
```

## Algorithm

1. The K-Means algorithm start by randomly choose k instances as k centroids.<br/>
2. Then label the instances by assigning each of them to the cluster whose centroid is closest.<br/>
3. Then update the centroids by computing the mean of the instances for each cluster.<br/>
4. Repeat the previous two steps until the centroids stops moving.

```{image} ../images/kmeans.png
:alt: kmeans
:width: 500px
:align: center
```

## Convergence

Define the distortion function:

$$J(c, \mu) = \sum_{i=1}^{n}\left \| x^{(i)} - \mu_{c^{(i)}} \right \|^{2} $$

K-Means is exactly coordinate descent on $J$.

label instance step minimize $J(c, \mu)$ while keeping the centroids fixed.

update centroids step minimize $J(c, \mu)$ while keeping the cluster fixed.

$J(c, \mu)$ monotony decrease with lower bound, thus convergence.

## Examples

In [1]:
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])
# k need to specified
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [2]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])

In [3]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0], dtype=int32)

In [4]:
# If you happen to kown approximately where the centroids should be,
# set `good_init` to these centroids.
good_init = np.array([[-3, 3], [-3, 2], [-3, 1], [-1, 2], [0, 2]])

# n_init: The number of random initializations default 10.
KMeans(n_clusters=5, init=good_init, n_init=1)

KMeans(init=array([[-3,  3],
       [-3,  2],
       [-3,  1],
       [-1,  2],
       [ 0,  2]]),
       n_clusters=5, n_init=1)

## Selecting the Number of Clusters

In [5]:
"""
sklearn uses inertia to choose from 'n_init' models.
which is the mean squared distance between each instance and its closest centroid.
"""
# select k that is the elbow
kmeans.inertia_

16.0

Another more precise metric is called sihouette score, which is equal to:

$$\frac{b - a}{max(a, b)}$$

where a is the mean distance to the other instances in the same cluster.

b is the the mean distance to the instances of the next closest cluster, excluding the instance's own cluster.

In [6]:
from sklearn.metrics import silhouette_score

# select k that maximize silhouette
silhouette_score(X, kmeans.labels_)

0.7133477791749615

## Minibatch K-Means

In [7]:
"""
minibatch k-means is capable of using mini-batches,
moving the centroids just slightly at each iteration,
this speed up cluster & enable clustering huge datasets.
"""
from sklearn.cluster import MiniBatchKMeans

minibatch_kmeans = MiniBatchKMeans(n_clusters=5)
minibatch_kmeans.fit(X)

MiniBatchKMeans(n_clusters=5)